name = "scrutoscope"
main = "worker.js"
compatibility_date = "2024-09-23"

[[r2_buckets]]
binding = "REPORTS"
bucket_name = "scrutinizer-reports"

[durable_objects]
bindings = [
  { name = "RATE_LIMITER", class_name = "RateLimiterDO" }
]

[[migrations]]
tag = "v1"
new_classes = ["RateLimiterDO"]

[[rules]]
type = "Text"
globs = ["**/scrutinizer-timeline.js"]
fallthrough = true

[triggers]
crons = ["0 4 * * *"]
